### ISSUE TITLE
error while installing the extension TU Delft

### ISSUE THREAD

**Issue by oliviergimenez** [pat-alt/pat-alt.github.io#18]
Hi Patrick,

I'd like to use your quarto extension for a TU Delft theme for a talk. It's awesome by the way, thanks for making it public ! I'm particularly inspired by your recent talk https://github.com/pat-alt/pat-alt.github.io/tree/main/content/talks/posts/2023-ieee-satml that I'd like to reproduce to better understand how the template works.

However when trying to install it using the instructions in the Readme, I get:

> ERROR: The extension TU Delft is incompatible with this quarto version.
> 
> Extension requires: >=99.9.0
> Quarto version: 1.3.353
> 
> Error: The extension TU Delft is incompatible with this quarto version.
> 
> Extension requires: >=99.9.0
> Quarto version: 1.3.353
>     at validateExtension (file:///Applications/quarto/bin/quarto.js:59606:15)
>     at readExtension (file:///Applications/quarto/bin/quarto.js:59682:5)
>     at async loadExtension (file:///Applications/quarto/bin/quarto.js:59386:32)
>     at async Object.extension (file:///Applications/quarto/bin/quarto.js:59292:28)
>     at async readExtensionFormat (file:///Applications/quarto/bin/quarto.js:83227:27)
>     at async resolveFormats (file:///Applications/quarto/bin/quarto.js:83173:35)
>     at async renderContexts (file:///Applications/quarto/bin/quarto.js:82635:21)
>     at async Object.renderFormats (file:///Applications/quarto/bin/quarto.js:82686:26)
>     at async inputTargetIndex (file:///Applications/quarto/bin/quarto.js:83502:21)
>     at async resolveInputTarget (file:///Applications/quarto/bin/quarto.js:83581:19)

Any idea how to fix the issue? Note that I've just updated RStudio, and quarto. 

Cheers,
Olivier

**Comment by pat-alt** [comment]
Hi Oliver, thank you - glad to see the template being used!

The extensions currently requires the dev version of Quarto (something I will fix in the future, but I'm currently busy with a paper). You can install the dev version of Quarto as follows:

```zsh
git clone https://github.com/quarto-dev/quarto-cli
cd quarto-cli
./configure.sh
```

**Comment by pat-alt** [comment]
- [ ] change requirement in [yml](https://github.com/pat-alt/quarto-tudelft/blob/b324cee4a6860a5ed5385dc607330d49de052875/_extensions/tudelft/_extension.yml#LL4C28-L4C28)
- [ ] check if error persists

**Comment by oliviergimenez** [comment]
Thanks!
